on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create file and commit
      run: |
        set -x
        FILE="brick_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Another brick in the Green Wall" > "$FILE"
          echo "Brick number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -o 'Brick number: [0-9]*' "$FILE" | awk '{print $3}')
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/Brick number: /c\Brick number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "ClowerJ"
        git config --global user.email "jclowers18@gmail.com"
        git add "$FILE"
        git commit -m "Green wall engaged - Brick $NEXT_COUNT"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Debugging Step
      run: |
        cat brick_number.md
        git config --list
