name: ClowerJ's Daily Commit

on:
  schedule:
    - cron: '30 15 * * *'  # Runs every day at 3:30 PM UTC, which is 9:30 AM CST

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main 

    - name: Create file and commit
      run: |
        FILE="brick_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Another brick in the green wall" > "$FILE"
          echo "brick number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'brick number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/brick number: /c\brick number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "ClowerJ"
        git config --global user.email "jclowers18@gmail.com"
        git add "$FILE"
        git commit -m "Another brick in the green wall"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ClowerJ/GreenWall.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
